name: oopquiz
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: "3.24.3"  
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  flutter_code_editor: ^0.3.2
  markdown_widget: ^2.3.2+6
  path: ^1.9.0
  path_provider: ^2.1.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  icons_launcher: ^3.0.0
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
  - assets/congrats.gif
  - assets/animation/winanimation.json
  - assets/topics/
  - assets/logo.png
  
  fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Regular.ttf
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 700
